[package]
name = "yauid-sys-rs"
version = "0.1.1"
authors = ["Alexey Voznyuk <me@swizard.info>"]
links = "yauid"
build = "build.rs"

[lib]
name = "yauid_sys"

[dependencies]
libc = "0.2"

[build-dependencies]
gcc = "0.3"
